### ISSUE TITLE
Show call to action on logged user button to log out

### ISSUE THREAD

**Issue by jenkin** [teamdigitale/daf-nteract#101]
**Describe the bug**
Login button on the top left corner contains a simple call to action (cta): log in (with entering icon).

![Screenshot_20190528_121310](https://user-images.githubusercontent.com/426495/58470713-93dbf000-8142-11e9-96cd-2ab2b7a602bb.png)

After the authentication the same button contains username (so, no more cta) and only an icon (the exiting one) to describe the click effect: log out.

![Screenshot_20190528_121210](https://user-images.githubusercontent.com/426495/58470527-2a5be180-8142-11e9-8446-b36078f765e0.png)

Maybe you can separate the elements (after login, the username and an independent log out button) or add a tooltip (ie. a simple title attribute) with the cta (log out).

**Comment by and0111** [comment]
@jenkin @giux78 What about this?
![image](https://user-images.githubusercontent.com/32514668/59106998-fd74af00-8937-11e9-93bb-0c36004cdc8d.png)

**Comment by jenkin** [comment]
Ok, va bene... :)
